typography_spectrum: 0.18164
color:
  brandColors:
    - '#060608'
    - '#fa6921'
    - '#fcfdf9'
    - '#eebd2b'
    - '#2bf7f1'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: UA-82277519-1
  facebook: null
  twitter: null
name: Hirofumi Tanigami
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Facebook
    url: 'https://www.facebook.com/tanigami'
    type: external
  - name: WAGG
    url: 'https://wagg.jp/'
    type: external
  - name: OMIMI
    url: 'https://omimi.tanigami.wtf/'
    type: external
  - name: GitHub
    url: 'https://github.com/tanigami'
    type: external
favicon: null
title: ''
purpose: []
