name: Hirofumi Tanigami
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25801
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060608'
    - '#fa6921'
    - '#fcfdf9'
    - '#eebd2b'
    - '#2bf7f1'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
